/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/healthz": {
    /** Healthz */
    get: operations["healthz_healthz_get"];
  };
  "/v1/ping": {
    /** Ping */
    get: operations["ping_v1_ping_get"];
  };
  "/v1/clients": {
    /** List Clients */
    get: operations["list_clients_v1_clients_get"];
    /** Create Client */
    post: operations["create_client_v1_clients_post"];
  };
  "/v1/clients/{client_id}": {
    /** Get Client */
    get: operations["get_client_v1_clients__client_id__get"];
    /** Update Client */
    patch: operations["update_client_v1_clients__client_id__patch"];
  };
  "/v1/appointments": {
    /** List Appointments */
    get: operations["list_appointments_v1_appointments_get"];
    /** Create Appointment */
    post: operations["create_appointment_v1_appointments_post"];
  };
  "/v1/appointments/{appointment_id}": {
    /** Delete Appointment */
    delete: operations["delete_appointment_v1_appointments__appointment_id__delete"];
    /** Update Appointment */
    patch: operations["update_appointment_v1_appointments__appointment_id__patch"];
  };
  "/v1/tasks/ping": {
    /** Enqueue Ping */
    post: operations["enqueue_ping_v1_tasks_ping_post"];
  };
  "/v1/tasks/slow-add": {
    /** Enqueue Slow Add */
    post: operations["enqueue_slow_add_v1_tasks_slow_add_post"];
  };
  "/v1/tasks/result/{task_id}": {
    /** Get Result */
    get: operations["get_result_v1_tasks_result__task_id__get"];
  };
  "/v1/calendar/events": {
    /** List Events */
    get: operations["list_events_v1_calendar_events_get"];
  };
  "/v1/auth/register": {
    /** Register User */
    post: operations["register_user_v1_auth_register_post"];
  };
  "/v1/auth/login": {
    /** Login User */
    post: operations["login_user_v1_auth_login_post"];
  };
  "/v1/auth/me": {
    /** Read Current User */
    get: operations["read_current_user_v1_auth_me_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** AppointmentCreate */
    AppointmentCreate: {
      /** Client Id */
      client_id: number;
      /**
       * Starts At
       * Format: date-time
       */
      starts_at: string;
      /**
       * Ends At
       * Format: date-time
       */
      ends_at: string;
      /** Notes */
      notes?: string | null;
    };
    /** AppointmentOut */
    AppointmentOut: {
      /** Client Id */
      client_id: number;
      /**
       * Starts At
       * Format: date-time
       */
      starts_at: string;
      /**
       * Ends At
       * Format: date-time
       */
      ends_at: string;
      /** Notes */
      notes?: string | null;
      /** Id */
      id: number;
    };
    /** AppointmentUpdate */
    AppointmentUpdate: {
      /** Client Id */
      client_id?: number | null;
      /** Starts At */
      starts_at?: string | null;
      /** Ends At */
      ends_at?: string | null;
      /** Notes */
      notes?: string | null;
    };
    /** ClientCreate */
    ClientCreate: {
      /** Name */
      name: string;
      /** Phone */
      phone: string;
    };
    /** ClientOut */
    ClientOut: {
      /** Name */
      name: string;
      /** Phone */
      phone: string;
      /** Id */
      id: number;
    };
    /** ClientUpdate */
    ClientUpdate: {
      /** Name */
      name?: string | null;
      /** Phone */
      phone?: string | null;
    };
    /** Event */
    Event: {
      /** Id */
      id: string;
      /** Summary */
      summary: string;
      /**
       * Start
       * Format: date-time
       */
      start: string;
      /**
       * End
       * Format: date-time
       */
      end: string;
      /** Location */
      location: string;
    };
    /** EventsResponse */
    EventsResponse: {
      /** Items */
      items: components["schemas"]["Event"][];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Token */
    Token: {
      /** Access Token */
      access_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type?: string;
    };
    /** UserCreate */
    UserCreate: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /** UserOut */
    UserOut: {
      /** Id */
      id: number;
      /**
       * Email
       * Format: email
       */
      email: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Healthz */
  healthz_healthz_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Ping */
  ping_v1_ping_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** List Clients */
  list_clients_v1_clients_get: {
    parameters: {
      query?: {
        /** @description Optional search by name or phone */
        q?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ClientOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Client */
  create_client_v1_clients_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ClientCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ClientOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Client */
  get_client_v1_clients__client_id__get: {
    parameters: {
      path: {
        client_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ClientOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Client */
  update_client_v1_clients__client_id__patch: {
    parameters: {
      path: {
        client_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ClientUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ClientOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Appointments */
  list_appointments_v1_appointments_get: {
    parameters: {
      query?: {
        /** @description Filter appointments starting after this datetime */
        date_from?: string | null;
        /** @description Filter appointments starting before this datetime */
        date_to?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AppointmentOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Appointment */
  create_appointment_v1_appointments_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AppointmentCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["AppointmentOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Appointment */
  delete_appointment_v1_appointments__appointment_id__delete: {
    parameters: {
      path: {
        appointment_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Appointment */
  update_appointment_v1_appointments__appointment_id__patch: {
    parameters: {
      path: {
        appointment_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AppointmentUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AppointmentOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Enqueue Ping */
  enqueue_ping_v1_tasks_ping_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Enqueue Slow Add */
  enqueue_slow_add_v1_tasks_slow_add_post: {
    parameters: {
      query: {
        a: number;
        b: number;
        delay?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Result */
  get_result_v1_tasks_result__task_id__get: {
    parameters: {
      path: {
        task_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Events */
  list_events_v1_calendar_events_get: {
    parameters: {
      query?: {
        max_results?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["EventsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Register User */
  register_user_v1_auth_register_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["UserOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Login User */
  login_user_v1_auth_login_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Token"];
        };
      };
    };
  };
  /** Read Current User */
  read_current_user_v1_auth_me_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserOut"];
        };
      };
    };
  };
}
