"""add user_id to clients and appointments
Revision ID: aa32e92a7101
Revises: 20251125130000
Create Date: 2025-12-06 00:31:49.761027
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'aa32e92a7101'
down_revision = '20251125130000'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # Add user_id columns as nullable first
    op.add_column('appointments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('user_id', sa.Integer(), nullable=True))

    # Assign existing records to the first user
    op.execute("""
        UPDATE clients
        SET user_id = (SELECT id FROM users ORDER BY id LIMIT 1)
        WHERE user_id IS NULL
    """)
    op.execute("""
        UPDATE appointments
        SET user_id = (SELECT id FROM users ORDER BY id LIMIT 1)
        WHERE user_id IS NULL
    """)

    # Now make the columns NOT NULL
    op.alter_column('appointments', 'user_id', nullable=False)
    op.alter_column('clients', 'user_id', nullable=False)

    # Add indexes and foreign keys
    op.create_index(op.f('ix_appointments_user_id'), 'appointments', ['user_id'], unique=False)
    op.create_foreign_key(None, 'appointments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_clients_user_id'), 'clients', ['user_id'], unique=False)
    op.create_foreign_key(None, 'clients', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    op.alter_column('google_credentials', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('google_credentials', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_index(op.f('ix_clients_user_id'), table_name='clients')
    op.drop_column('clients', 'user_id')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_index(op.f('ix_appointments_user_id'), table_name='appointments')
    op.drop_column('appointments', 'user_id')
    # ### end Alembic commands ###
