name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Static type check / import sanity
        working-directory: backend
        run: python -m compileall app
      - name: Alembic check (no-op upgrade)
        working-directory: backend
        env:
          DATABASE_URL: sqlite:///./tmp.db
        run: alembic upgrade head --sql > /dev/null
